# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineaTitulo = QtWidgets.QFrame(self.centralwidget)
        self.lineaTitulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lineaTitulo.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineaTitulo.setObjectName("lineaTitulo")
        self.gridLayout.addWidget(self.lineaTitulo, 0, 0, 1, 2)
        self.groupBoxImagenes = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxImagenes.setFont(font)
        self.groupBoxImagenes.setObjectName("groupBoxImagenes")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxImagenes)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollAreaImg = QtWidgets.QScrollArea(self.groupBoxImagenes)
        self.scrollAreaImg.setEnabled(True)
        self.scrollAreaImg.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollAreaImg.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollAreaImg.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollAreaImg.setWidgetResizable(True)
        self.scrollAreaImg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollAreaImg.setObjectName("scrollAreaImg")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 956, 517))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridImg = QtWidgets.QGridLayout()
        self.gridImg.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridImg.setContentsMargins(5, 5, 5, 5)
        self.gridImg.setHorizontalSpacing(6)
        self.gridImg.setObjectName("gridImg")
        self.gridLayout_3.addLayout(self.gridImg, 0, 0, 1, 1)
        self.scrollAreaImg.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollAreaImg, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxImagenes, 6, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 15, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.botonCreditos = QtWidgets.QPushButton(self.centralwidget)
        self.botonCreditos.setEnabled(True)
        self.botonCreditos.setMaximumSize(QtCore.QSize(15, 15))
        self.botonCreditos.setObjectName("botonCreditos")
        self.verticalLayout.addWidget(self.botonCreditos, 0, QtCore.Qt.AlignRight)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Schola")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.labelInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelInfo.setText("")
        self.labelInfo.setObjectName("labelInfo")
        self.verticalLayout.addWidget(self.labelInfo)
        self.barBuscando = QtWidgets.QProgressBar(self.centralwidget)
        self.barBuscando.setProperty("value", 0)
        self.barBuscando.setObjectName("barBuscando")
        self.verticalLayout.addWidget(self.barBuscando)
        self.gridLayout.addLayout(self.verticalLayout, 5, 1, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(30, 12, 0, -1)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.inputPalabra = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPalabra.setMaximumSize(QtCore.QSize(280, 16777215))
        self.inputPalabra.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.inputPalabra.setMaxLength(150)
        self.inputPalabra.setObjectName("inputPalabra")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inputPalabra)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.inputProb = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.inputProb.setMaximumSize(QtCore.QSize(280, 16777215))
        self.inputProb.setMaximum(1.0)
        self.inputProb.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.inputProb.setProperty("value", 0.5)
        self.inputProb.setObjectName("inputProb")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inputProb)
        self.botonBuscar = QtWidgets.QPushButton(self.centralwidget)
        self.botonBuscar.setObjectName("botonBuscar")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.botonBuscar)
        self.tipoOrdenacion = QtWidgets.QComboBox(self.centralwidget)
        self.tipoOrdenacion.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tipoOrdenacion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tipoOrdenacion.setObjectName("tipoOrdenacion")
        self.tipoOrdenacion.addItem("")
        self.tipoOrdenacion.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tipoOrdenacion)
        self.gridLayout.addLayout(self.formLayout, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.inputPalabra, self.inputProb)
        MainWindow.setTabOrder(self.inputProb, self.botonBuscar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Handwriten Page Image Word Searcher"))
        self.groupBoxImagenes.setTitle(_translate("MainWindow", "Imágenes"))
        self.botonCreditos.setText(_translate("MainWindow", "?"))
        self.label_4.setText(_translate("MainWindow", "Buscador de palabras en imágenes de páginas"))
        self.label.setText(_translate("MainWindow", "Palabra"))
        self.label_2.setText(_translate("MainWindow", "Probabilidad "))
        self.botonBuscar.setText(_translate("MainWindow", "Buscar"))
        self.tipoOrdenacion.setItemText(0, _translate("MainWindow", "Ordenación Descendente"))
        self.tipoOrdenacion.setItemText(1, _translate("MainWindow", "Ordenación Ascendente"))
